In [1]:
import numpy as np
a = np.array([range(i, i + 3) for i in [1, 2, 3]])

In [2]:
a

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [3]:
zero = np.zeros((2,2), dtype = int)
print(zero)

[[0 0]
 [0 0]]


In [4]:
ones = np.ones((3,3), dtype = float)
print(f"{ones} \n")
full = np.full((3, 4), 2.3)
print(f"{full} \n")
sequence = np.arange(5, 8, 1.1)
print(f"{sequence} \n")
space = np.linspace(0, 2, 3)
print(f"{space} \n")
random = np.random.random((2, 2))
print(f"{random} \n")
random_normal = np.random.normal(0, 1, (3, 3))
print(f"{random_normal} \n")
randint = np.random.randint(0, 10, (3, 3))
print(f"{randint} \n")
identity = np.eye(3)
print(f"{identity} \n")

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

[[2.3 2.3 2.3 2.3]
 [2.3 2.3 2.3 2.3]
 [2.3 2.3 2.3 2.3]] 

[5.  6.1 7.2] 

[0. 1. 2.] 

[[0.10319882 0.25096453]
 [0.06352089 0.75061112]] 

[[ 0.72285199 -1.02567395 -0.57258397]
 [-0.0154751   1.60573443 -1.30513778]
 [ 0.79435228  0.58131102 -0.18978021]] 

[[9 7 9]
 [0 3 2]
 [0 5 8]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 



In [26]:
a = np.eye(3)
b = np.random.randint(10, 14, (3, 3))

In [34]:
c = np.hstack([a, b, a])

In [35]:
c

array([[ 1.,  0.,  0., 13., 10., 13.,  1.,  0.,  0.],
       [ 0.,  1.,  0., 10., 10., 10.,  0.,  1.,  0.],
       [ 0.,  0.,  1., 10., 12., 13.,  0.,  0.,  1.]])

In [36]:
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
a[:, 1] = 2*a[:,1]

In [43]:
diagonal


array([0., 2., 0.])

In [44]:
a

array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 1.]])

In [52]:
ba = np.empty((2,3))

In [54]:
na = ba[[1,0 ]]

In [55]:
ba

array([[4.66722971e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [56]:
na

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [4.66722971e-310, 0.00000000e+000, 0.00000000e+000]])

In [98]:
arr = np.arange(32).reshape((8, 4))
z = arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]
z

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [96]:
z1 = arr[[1, 5, 7, 2]][[0, 1, 3, 2]]
z1

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [ 8,  9, 10, 11],
       [28, 29, 30, 31]])

In [64]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [92]:
z2 = arr[[1, 5, 7, 2]]
z2

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])