In [80]:
import numpy as np
a = np.array([[1, 2, 3, 4, 5]])
b = np.array([1, 2, 3, 4, 5])
z = np.add.outer(a, a)
a.shape

(1, 5)

In [74]:
np.sum(np.split(z, 5), axis = 0)

array([[20, 25, 30, 35, 40]])

In [70]:
sum(np.split(z, 5))

array([[20, 25, 30, 35, 40]])

In [65]:
np.add()

ValueError: non-broadcastable output operand with shape (5,) doesn't match the broadcast shape (2,5)

In [64]:
a

array([ 2,  4,  6,  8, 10])

In [105]:
a = np.arange(6).reshape((3, 2))
b = np.arange(3)
b = b[:, np.newaxis]
b
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [106]:
a +b

array([[0, 1],
       [3, 4],
       [6, 7]])

In [118]:
np.random.seed(42)
x = np.random.randn(100)
print(f"El valor de x es \n{x} \n")
# compute a histogram by hand
bins = np.linspace(-5, 5, 20)
print(f"El valor de bins es \n{bins} \n")
counts = np.zeros_like(bins)
print(f"El valor de counts es \n{counts}\n")
# find the appropriate bin for each x
i = np.searchsorted(bins, x)
print("El valor de i es: \n",i, "\n")
# add 1 to each of these bins
np.add.at(counts, i, 1)
print(counts)

El valor de x es 
[ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337 -0.23413696
  1.57921282  0.76743473 -0.46947439  0.54256004 -0.46341769 -0.46572975
  0.24196227 -1.91328024 -1.72491783 -0.56228753 -1.01283112  0.31424733
 -0.90802408 -1.4123037   1.46564877 -0.2257763   0.0675282  -1.42474819
 -0.54438272  0.11092259 -1.15099358  0.37569802 -0.60063869 -0.29169375
 -0.60170661  1.85227818 -0.01349722 -1.05771093  0.82254491 -1.22084365
  0.2088636  -1.95967012 -1.32818605  0.19686124  0.73846658  0.17136828
 -0.11564828 -0.3011037  -1.47852199 -0.71984421 -0.46063877  1.05712223
  0.34361829 -1.76304016  0.32408397 -0.38508228 -0.676922    0.61167629
  1.03099952  0.93128012 -0.83921752 -0.30921238  0.33126343  0.97554513
 -0.47917424 -0.18565898 -1.10633497 -1.19620662  0.81252582  1.35624003
 -0.07201012  1.0035329   0.36163603 -0.64511975  0.36139561  1.53803657
 -0.03582604  1.56464366 -2.6197451   0.8219025   0.08704707 -0.29900735
  0.09176078 -1.98756891 -0.21967

In [119]:
np.hist?

Object `np.hist` not found.
