# Regresión lineal en python

## Paquete skit-learn para regreseion lineal y la selección de rasgos

In [12]:
from sklearn.feature_selection import RFE #elige cuales son los mayores pesos
from sklearn.svm import SVR #super vector machine
import pandas as pd
import numpy as np

In [13]:
root = '/home/giovannyencinia/Documents/datasets/MACHINE_LEARNING_course'
path = root + '/ads/Advertising.csv'
ads = pd.read_csv(path)

In [14]:
features_cols = ['TV', 'Radio', 'Newspaper']
X = ads[features_cols]
y = ads.Sales

In [27]:
estimator = SVR(kernel='linear') #elige el modelo a usar
selector = RFE(estimator, 2, step = 1) # recursive feature elimination
selector = selector.fit(X, y)

In [28]:
selector.support_ # muestra que columnas son las que se deben tener en cuenta

array([ True,  True, False])

In [29]:
selector.ranking_ # El ranking de las columnas a usar

array([1, 1, 2])

In [30]:
from sklearn.linear_model import LinearRegression

In [31]:
X_pred = X[['TV', 'Radio']]

In [32]:
model_ads = LinearRegression() #Define model
model_ads.fit(X_pred, y) #fit model, se entrena el modelo

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [33]:
model_ads.coef_

array([0.04575482, 0.18799423])

In [34]:
model_ads.intercept_

2.921099912405138

y = 2.921099912405138 + 0.04575482TV + 0.18799423Radio

In [35]:
model_ads.score(X_pred, y)

0.8971942610828956