# Test

In [65]:
import numpy as np
elementos=np.arange(16)
x=np.arange(0,8,.5)
print(x)
print(elementos)
elementos[x%2==0]



[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


array([ 0,  4,  8, 12])

In [55]:
matriz2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [1]:
!ls

anaconda3		 Documents	 Public     rtlwifi_new		 Videos
AprendiendoPython.ipynb  Downloads	 R	    SpyderLinearAlgebra
bookmarks.html		 LearningPython  Rcourse    Templates
broadcom-wl-4.150.10.5	 Music		 reshape    Trabajo
Desktop			 Pictures	 rtl8821ce  Untitled.ipynb


In [3]:
import jupyterthemes as jt

In [4]:
jt -l

NameError: name 'l' is not defined

In [3]:
16362/375498


0.043574133550644746

In [2]:
375498*.22



82609.56