In [2]:
import numpy as np

In [3]:
identidad=np.identity(9)

In [4]:
mat=np.random.random((3,3))
print(mat)

[[0.9761238  0.83376298 0.8494647 ]
 [0.77624424 0.56383967 0.26013422]
 [0.71329698 0.32163251 0.78626618]]


In [5]:
np.ravel(mat) #ravel crea un vector a partir de una matriz

array([0.9761238 , 0.83376298, 0.8494647 , 0.77624424, 0.56383967,
       0.26013422, 0.71329698, 0.32163251, 0.78626618])

In [6]:
print(mat.argmax()) #arroja el indice del elemento más grande de la matriz, pero lo muestra 
print(mat.max()) #muestra el elemento másd grande de la matriz

0
0.9761238027972645


In [7]:
np.unravel_index(mat.argmax(),mat.shape,)

(0, 0)

In [13]:
np.unravel_index(mat.argmin(),mat.shape)


(1, 2)

In [9]:
np.unravel_index((mat.argmax(),mat.argmin()),mat.shape,order='C')
#Podemos encontrar mas de un valor, se separaran tuplas en las cuales se contendran 
#valores en x, y, z...

(array([0, 1]), array([0, 2]))

In [10]:
np.unravel_index((mat.argmax(),mat.argmin()),mat.shape,order='F')

(array([0, 2]), array([0, 1]))